CREATE TABLE LS_REQUEST (
    KOD INT AUTO_INCREMENT PRIMARY KEY,
    LSCODE INT NOT NULL,
    DDOC TIMESTAMP NOT NULL,
    CMDIN BLOB,
    STATE SMALLINT NOT NULL,
    ERR VARCHAR(250)
);

CREATE TABLE LS_RESPONSE (
    KOD INT AUTO_INCREMENT PRIMARY KEY,
    LSCODE INT NOT NULL,
    DDOC TIMESTAMP NOT NULL,
    CMDOUT BLOB,
    STATE SMALLINT NOT NULL,
    ERR VARCHAR(250)
);